
export const APP_DATA_UPDATE = 'APP_DATA_UPDATE'

export const APP_FIREBASE_REFERENCE_UPDATE = 'APP_FIREBASE_REFERENCE_UPDATE'

export const UPDATE_LOGIN_PROGRESS = 'UPDATE_LOGIN_PROGRESS'
export const INVENTARY_UPDATE_ITEMS = 'INVENTARY_UPDATE_ITEMS'
export const MEETINGS_UPDATE_ITEMS = 'MEETINGS_UPDATE_ITEMS'
export const STATUTES_UPDATE_ITEMS = 'STATUTES_UPDATE_ITEMS'
